package com.javath.mapping;

// Generated Sep 29, 2014 1:56:13 PM by Hibernate Tools 4.0.0

/**
 * SetAccount generated by hbm2java
 */
public class SetAccount implements java.io.Serializable {

	private Integer id;
	private int brokerId;
	private String username;
	private String password;

	public SetAccount() {
	}

	public SetAccount(int brokerId, String username) {
		this.brokerId = brokerId;
		this.username = username;
	}

	public SetAccount(int brokerId, String username, String password) {
		this.brokerId = brokerId;
		this.username = username;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getBrokerId() {
		return this.brokerId;
	}

	public void setBrokerId(int brokerId) {
		this.brokerId = brokerId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
