package com.javath.mapping;

// Generated Sep 23, 2014 1:12:15 PM by Hibernate Tools 4.0.0

/**
 * SetBrokerId generated by hbm2java
 */
public class SetBrokerId implements java.io.Serializable {

	private int extendId;
	private String username;

	public SetBrokerId() {
	}

	public SetBrokerId(int extendId, String username) {
		this.extendId = extendId;
		this.username = username;
	}

	public int getExtendId() {
		return this.extendId;
	}

	public void setExtendId(int extendId) {
		this.extendId = extendId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SetBrokerId))
			return false;
		SetBrokerId castOther = (SetBrokerId) other;

		return (this.getExtendId() == castOther.getExtendId())
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getExtendId();
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
