package com.javath.mapping;

// Generated Sep 10, 2014 9:53:57 AM by Hibernate Tools 4.0.0

/**
 * SetBroker generated by hbm2java
 */
public class SetBroker implements java.io.Serializable {

	private Integer id;
	private String classname;
	private String username;
	private String password;

	public SetBroker() {
	}

	public SetBroker(String classname, String username, String password) {
		this.classname = classname;
		this.username = username;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
