package com.javath.mapping;

// Generated Sep 29, 2014 1:56:13 PM by Hibernate Tools 4.0.0

/**
 * SetBroker generated by hbm2java
 */
public class SetBroker implements java.io.Serializable {

	private Integer id;
	private String classname;

	public SetBroker() {
	}

	public SetBroker(String classname) {
		this.classname = classname;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

}
