package com.javath.mapping;

// Generated Sep 23, 2014 1:12:15 PM by Hibernate Tools 4.0.0

/**
 * SetBroker generated by hbm2java
 */
public class SetBroker implements java.io.Serializable {

	private SetBrokerId id;
	private String password;

	public SetBroker() {
	}

	public SetBroker(SetBrokerId id) {
		this.id = id;
	}

	public SetBroker(SetBrokerId id, String password) {
		this.id = id;
		this.password = password;
	}

	public SetBrokerId getId() {
		return this.id;
	}

	public void setId(SetBrokerId id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
