package com.javath.mapping;

// Generated Jul 10, 2014 2:01:01 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SetCompany generated by hbm2java
 */
public class SetCompany implements java.io.Serializable {

	private String symbol;
	private String nameTh;
	private String nameEn;
	private String website;
	private Date update;

	public SetCompany() {
	}

	public SetCompany(String symbol) {
		this.symbol = symbol;
	}

	public SetCompany(String symbol, String nameTh, String nameEn,
			String website, Date update) {
		this.symbol = symbol;
		this.nameTh = nameTh;
		this.nameEn = nameEn;
		this.website = website;
		this.update = update;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public String getNameTh() {
		return this.nameTh;
	}

	public void setNameTh(String nameTh) {
		this.nameTh = nameTh;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Date getUpdate() {
		return this.update;
	}

	public void setUpdate(Date update) {
		this.update = update;
	}

}
