package com.javath.mapping;

// Generated Sep 23, 2014 1:12:15 PM by Hibernate Tools 4.0.0

/**
 * SetExtendsBroker generated by hbm2java
 */
public class SetExtendsBroker implements java.io.Serializable {

	private Integer id;
	private String classname;

	public SetExtendsBroker() {
	}

	public SetExtendsBroker(String classname) {
		this.classname = classname;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

}
