package com.javath.mapping;

// Generated Jul 10, 2014 2:01:01 PM by Hibernate Tools 4.0.0

/**
 * SetIndustry generated by hbm2java
 */
public class SetIndustry implements java.io.Serializable {

	private Short id;
	private String nameTh;
	private String nameEn;
	private Short marketId;

	public SetIndustry() {
	}

	public SetIndustry(String nameTh, String nameEn, Short marketId) {
		this.nameTh = nameTh;
		this.nameEn = nameEn;
		this.marketId = marketId;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getNameTh() {
		return this.nameTh;
	}

	public void setNameTh(String nameTh) {
		this.nameTh = nameTh;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public Short getMarketId() {
		return this.marketId;
	}

	public void setMarketId(Short marketId) {
		this.marketId = marketId;
	}

}
