package com.javath.mapping;

// Generated Sep 29, 2014 1:56:13 PM by Hibernate Tools 4.0.0

/**
 * SetPlan generated by hbm2java
 */
public class SetPlan implements java.io.Serializable {

	private Integer id;
	private int accountId;
	private String symbol;
	private int strategyId;

	public SetPlan() {
	}

	public SetPlan(int accountId, String symbol, int strategyId) {
		this.accountId = accountId;
		this.symbol = symbol;
		this.strategyId = strategyId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public int getStrategyId() {
		return this.strategyId;
	}

	public void setStrategyId(int strategyId) {
		this.strategyId = strategyId;
	}

}
