package com.javath.mapping;

// Generated Jul 10, 2014 2:01:01 PM by Hibernate Tools 4.0.0

/**
 * SetSector generated by hbm2java
 */
public class SetSector implements java.io.Serializable {

	private Short id;
	private String nameTh;
	private String nameEn;
	private Short industryId;

	public SetSector() {
	}

	public SetSector(String nameTh, String nameEn, Short industryId) {
		this.nameTh = nameTh;
		this.nameEn = nameEn;
		this.industryId = industryId;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getNameTh() {
		return this.nameTh;
	}

	public void setNameTh(String nameTh) {
		this.nameTh = nameTh;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public Short getIndustryId() {
		return this.industryId;
	}

	public void setIndustryId(Short industryId) {
		this.industryId = industryId;
	}

}
