package com.javath.mapping;
// Generated Aug 6, 2014 8:47:29 AM by Hibernate Tools 4.0.0



/**
 * SettradeQuote generated by hbm2java
 */
public class SettradeQuote  implements java.io.Serializable {


     private SettradeQuoteId id;
     private Double open;
     private Double high;
     private Double low;
     private Double last;
     private Double changePrior;
     private Double bid;
     private Long bidVolume;
     private Double offer;
     private Long offerVolume;
     private Long volume;
     private Double value;

    public SettradeQuote() {
    }

	
    public SettradeQuote(SettradeQuoteId id) {
        this.id = id;
    }
    public SettradeQuote(SettradeQuoteId id, Double open, Double high, Double low, Double last, Double changePrior, Double bid, Long bidVolume, Double offer, Long offerVolume, Long volume, Double value) {
       this.id = id;
       this.open = open;
       this.high = high;
       this.low = low;
       this.last = last;
       this.changePrior = changePrior;
       this.bid = bid;
       this.bidVolume = bidVolume;
       this.offer = offer;
       this.offerVolume = offerVolume;
       this.volume = volume;
       this.value = value;
    }
   
    public SettradeQuoteId getId() {
        return this.id;
    }
    
    public void setId(SettradeQuoteId id) {
        this.id = id;
    }
    public Double getOpen() {
        return this.open;
    }
    
    public void setOpen(Double open) {
        this.open = open;
    }
    public Double getHigh() {
        return this.high;
    }
    
    public void setHigh(Double high) {
        this.high = high;
    }
    public Double getLow() {
        return this.low;
    }
    
    public void setLow(Double low) {
        this.low = low;
    }
    public Double getLast() {
        return this.last;
    }
    
    public void setLast(Double last) {
        this.last = last;
    }
    public Double getChangePrior() {
        return this.changePrior;
    }
    
    public void setChangePrior(Double changePrior) {
        this.changePrior = changePrior;
    }
    public Double getBid() {
        return this.bid;
    }
    
    public void setBid(Double bid) {
        this.bid = bid;
    }
    public Long getBidVolume() {
        return this.bidVolume;
    }
    
    public void setBidVolume(Long bidVolume) {
        this.bidVolume = bidVolume;
    }
    public Double getOffer() {
        return this.offer;
    }
    
    public void setOffer(Double offer) {
        this.offer = offer;
    }
    public Long getOfferVolume() {
        return this.offerVolume;
    }
    
    public void setOfferVolume(Long offerVolume) {
        this.offerVolume = offerVolume;
    }
    public Long getVolume() {
        return this.volume;
    }
    
    public void setVolume(Long volume) {
        this.volume = volume;
    }
    public Double getValue() {
        return this.value;
    }
    
    public void setValue(Double value) {
        this.value = value;
    }




}


